#AntiGrief Settings

#Message Setting
message: "change in config.yml"

#Features Settings

#anti drop items
#Options: true/false
enable-antidropitems: true

#anti break blocks
#Options: true/false
enable-antibreakblocks: true

#anti place blocks
#Options: true/false
enable-antiplaceblocks: true

#anti explode
#Options: true/false:
enable-antiexplode: true